<?php
declare(strict_types=1);
namespace PWT\Staff\Admin;
defined('ABSPATH') || exit;
use PWT\Staff\Operations\TaskRepository;
use PWT\Staff\Operations\OperationsRepository;
use PWT\Staff\Roles\Capabilities;

final class ManagerControlCentre {
 public function register(): void { add_action('admin_menu',[$this,'menu']); add_action('admin_notices',[$this,'notices']); }
 public function menu(): void { add_submenu_page('pwt-dashboard',__('Operations Control Centre','wildtours-plugin'),__('Control Centre','wildtours-plugin'),Capabilities::MANAGE_STAFF,'pwt-operations-control',[$this,'render']); }
 private function taskData($t): array { return ['id'=>$t->ID,'title'=>$t->post_title,'booking'=>(int)get_post_meta($t->ID,'_pwt_task_booking_id',true),'assignee'=>(int)get_post_meta($t->ID,'_pwt_task_assignee',true),'status'=>(string)get_post_meta($t->ID,'_pwt_task_status',true),'due'=>(string)get_post_meta($t->ID,'_pwt_task_due_date',true),'priority'=>(string)get_post_meta($t->ID,'_pwt_task_priority',true),'blocked'=>(string)get_post_meta($t->ID,'_pwt_task_blocked_reason',true)]; }
 public function notices(): void { if(!current_user_can(Capabilities::MANAGE_STAFF)) return; $tasks=(new TaskRepository())->tasks(); $over=0;$blocked=0;$today=wp_date('Y-m-d'); foreach($tasks as $t){$d=$this->taskData($t); if($d['status']==='blocked')$blocked++; if($d['due'] && $d['due']<$today && $d['status']!=='completed')$over++;} if($over||$blocked) echo '<div class="notice notice-warning"><p><strong>PWT Operations:</strong> '.sprintf(esc_html__('%d overdue and %d blocked task(s) require attention.','wildtours-plugin'),$over,$blocked).' <a href="'.esc_url(admin_url('admin.php?page=pwt-operations-control')).'">'.esc_html__('Open Control Centre','wildtours-plugin').'</a></p></div>'; }
 public function render(): void { if(!current_user_can(Capabilities::MANAGE_STAFF))wp_die(esc_html__('You do not have permission.','wildtours-plugin')); $repo=new TaskRepository();$tasks=$repo->tasks();$today=wp_date('Y-m-d');$tomorrow=wp_date('Y-m-d',strtotime('+1 day'));$stats=['overdue'=>0,'blocked'=>0,'today'=>0,'tomorrow'=>0,'unassigned'=>0];$work=[];$risk=[];foreach($tasks as $t){$d=$this->taskData($t);$name=$d['assignee']?(get_userdata($d['assignee'])->display_name??('User #'.$d['assignee'])):'Unassigned';$work[$name]=($work[$name]??0)+($d['status']!=='completed');if(!$d['assignee'])$stats['unassigned']++;if($d['status']==='blocked'){$stats['blocked']++;$risk[]=$d;}if($d['due']===$today&&$d['status']!=='completed')$stats['today']++;if($d['due']===$tomorrow&&$d['status']!=='completed')$stats['tomorrow']++;if($d['due']&&$d['due']<$today&&$d['status']!=='completed'){$stats['overdue']++;$risk[]=$d;}} echo '<div class="wrap"><h1>'.esc_html__('PWT Operations Control Centre','wildtours-plugin').'</h1><p>'.esc_html__('Manager view of operational risk, workload and upcoming departures.','wildtours-plugin').'</p><div style="display:flex;gap:12px;flex-wrap:wrap;margin:20px 0">';foreach($stats as $k=>$v)echo '<div class="card" style="min-width:150px;padding:14px"><strong>'.esc_html(ucwords(str_replace('_',' ',$k))).'</strong><h2>'.esc_html((string)$v).'</h2></div>';echo '</div><h2>'.esc_html__('Staff Workload','wildtours-plugin').'</h2><table class="widefat striped"><thead><tr><th>Staff</th><th>Open Tasks</th></tr></thead><tbody>';foreach($work as $n=>$c)echo '<tr><td>'.esc_html($n).'</td><td>'.esc_html((string)$c).'</td></tr>';if(!$work)echo '<tr><td colspan="2">No open tasks.</td></tr>';echo '</tbody></table><h2>'.esc_html__('Booking Risk Indicators','wildtours-plugin').'</h2><table class="widefat striped"><thead><tr><th>Task</th><th>Booking</th><th>Assignee</th><th>Status</th><th>Due</th><th>Blocked Reason</th></tr></thead><tbody>';foreach($risk as $d){$booking=$d['booking']?get_the_title($d['booking']):'—';$u=$d['assignee']?get_userdata($d['assignee']):null;echo '<tr><td>'.esc_html($d['title']).'</td><td>'.esc_html($booking).'</td><td>'.esc_html($u?$u->display_name:'Unassigned').'</td><td>'.esc_html($d['status']).'</td><td>'.esc_html($d['due']?:'—').'</td><td>'.esc_html($d['blocked']?:'—').'</td></tr>';}if(!$risk)echo '<tr><td colspan="6">No current operational risks.</td></tr>';echo '</tbody></table><h2>'.esc_html__('Automatic Escalation Rules','wildtours-plugin').'</h2><ul><li>Blocked tasks are highlighted immediately to Operations Managers.</li><li>Tasks overdue beyond their due date are shown as operational risk.</li><li>Unassigned tasks are counted separately to prevent ownership gaps.</li><li>Today and tomorrow workload is surfaced for daily planning.</li></ul></div>'; }
}
