<?php
declare(strict_types=1);
namespace PWT\Staff\Admin;
defined('ABSPATH') || exit;
use PWT\Staff\Operations\TaskRepository;
final class OperationsTaskBoard {
 public function __construct(private TaskRepository $tasks){}
 public function register(): void { add_action('admin_menu',fn()=>add_submenu_page('pwt-staff','Operations Task Board','Task Board','pwt_access_staff_dashboard','pwt-operations-tasks',[$this,'page'])); add_action('admin_post_pwt_save_ops_task',[$this,'save']); }
 public function page(): void { if(!current_user_can('pwt_access_staff_dashboard')) wp_die('Not allowed'); $tasks=$this->tasks->tasks(current_user_can('pwt_manage_staff')?[]:['assignee'=>get_current_user_id()]); echo '<div class="wrap"><h1>Operations Task Board</h1><p>Track travel operations tasks, priorities, deadlines, blockers and completion.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="pwt_save_ops_task">'.wp_nonce_field('pwt_ops_task','_wpnonce',true,false).'<table class="form-table"><tr><th>Task</th><td><input required name="title" class="regular-text"></td></tr><tr><th>Booking ID</th><td><input name="booking_id" type="number"></td></tr><tr><th>Assignee</th><td>'.$this->users().'</td></tr><tr><th>Priority</th><td><select name="priority"><option>normal</option><option>low</option><option>high</option><option>urgent</option></select></td></tr><tr><th>Due date</th><td><input name="due_date" type="date"></td></tr><tr><th>Description</th><td><textarea name="description" rows="4" class="large-text"></textarea></td></tr></table><p><button class="button button-primary">Create Task</button></p></form><h2>Tasks</h2><table class="widefat striped"><thead><tr><th>Task</th><th>Booking</th><th>Assignee</th><th>Priority</th><th>Status</th><th>Due</th></tr></thead><tbody>'; foreach($tasks as $t){$m=fn($k)=>get_post_meta($t->ID,'_pwt_task_'.$k,true); $u=get_user_by('id',(int)$m('assignee')); echo '<tr><td>'.esc_html($t->post_title).'</td><td>'.esc_html($m('booking_id')).'</td><td>'.esc_html($u? $u->display_name:'Unassigned').'</td><td>'.esc_html($m('priority')).'</td><td>'.esc_html($m('status')?:'open').'</td><td>'.esc_html($m('due_date')).'</td></tr>';} echo '</tbody></table></div>'; }
 private function users(): string { $h='<select name="assignee"><option value="">Unassigned</option>'; foreach(get_users(['number'=>200]) as $u) $h.='<option value="'.(int)$u->ID.'">'.esc_html($u->display_name).'</option>'; return $h.'</select>'; }
 public function save(): void { if(!current_user_can('pwt_access_staff_dashboard')) wp_die('Not allowed'); check_admin_referer('pwt_ops_task'); $this->tasks->create(['title'=>$_POST['title']??'','booking_id'=>(int)($_POST['booking_id']??0),'assignee'=>(int)($_POST['assignee']??0),'priority'=>sanitize_key($_POST['priority']??'normal'),'due_date'=>sanitize_text_field($_POST['due_date']??''),'description'=>$_POST['description']??'','status'=>'open','created_by'=>get_current_user_id()]); wp_safe_redirect(admin_url('admin.php?page=pwt-operations-tasks')); exit; }
}
