<?php
declare(strict_types=1);
namespace PWT\Staff\Admin;
defined('ABSPATH') || exit;
use PWT\Staff\Trips\TripRepository;
final class TripOperationsBoard {
 public function __construct(private TripRepository $trips){}
 public function register(): void { add_action('admin_menu',fn()=>add_submenu_page('pwt-dashboard','Trip Operations','Trip Operations','pwt_access_staff_dashboard','pwt-trip-operations',[$this,'page'])); add_action('admin_post_pwt_save_trip_operation',[$this,'save']); }
 public function page(): void { if(!current_user_can('pwt_access_staff_dashboard')) wp_die('Not allowed'); $today=current_time('Y-m-d'); $tomorrow=wp_date('Y-m-d',strtotime('+1 day',current_time('timestamp'))); $todayTrips=$this->trips->trips(['date'=>$today]); $tomTrips=$this->trips->trips(['date'=>$tomorrow]); echo '<div class="wrap"><h1>Tour Departure & Live Trip Operations</h1><p>Manage departure manifests, pickup, safari, hotel status, incidents and tour completion.</p><h2>Today\'s Departures</h2>'.$this->table($todayTrips).'<h2>Tomorrow\'s Departures</h2>'.$this->table($tomTrips).'<hr><h2>Create Trip Operation</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="pwt_save_trip_operation">'.wp_nonce_field('pwt_trip_operation','_wpnonce',true,false).'<table class="form-table"><tr><th>Trip title</th><td><input required class="regular-text" name="title"></td></tr><tr><th>Booking ID</th><td><input type="number" name="booking_id"></td></tr><tr><th>Departure date</th><td><input required type="date" name="departure_date" value="'.esc_attr($today).'"></td></tr><tr><th>Guest manifest</th><td><textarea class="large-text" rows="3" name="guest_manifest" placeholder="Guest names, guest count, special requirements"></textarea></td></tr><tr><th>Emergency / operational notes</th><td><textarea class="large-text" rows="3" name="emergency_notes"></textarea></td></tr></table><p><button class="button button-primary">Create Trip Operation</button></p></form></div>'; }
 private function table(array $trips): string { $h='<table class="widefat striped"><thead><tr><th>Trip</th><th>Booking</th><th>Pickup</th><th>Safari</th><th>Hotel</th><th>Status</th><th>Incident</th></tr></thead><tbody>'; if(!$trips)$h.='<tr><td colspan="7">No trips scheduled.</td></tr>'; foreach($trips as $t){$m=fn($k)=>get_post_meta($t->ID,'_pwt_trip_'.$k,true);$h.='<tr><td>'.esc_html($t->post_title).'</td><td>'.esc_html($m('booking_id')).'</td><td>'.esc_html($m('pickup_status')?:'pending').'</td><td>'.esc_html($m('safari_status')?:'pending').'</td><td>'.esc_html($m('hotel_status')?:'pending').'</td><td>'.esc_html($m('status')?:'scheduled').'</td><td>'.($m('incident_report')?'Reported':'—').'</td></tr>';} return $h.'</tbody></table>'; }
 public function save(): void { if(!current_user_can('pwt_access_staff_dashboard')) wp_die('Not allowed'); check_admin_referer('pwt_trip_operation'); $this->trips->create(['title'=>$_POST['title']??'','booking_id'=>(int)($_POST['booking_id']??0),'departure_date'=>sanitize_text_field($_POST['departure_date']??''),'guest_manifest'=>sanitize_textarea_field($_POST['guest_manifest']??''),'emergency_notes'=>sanitize_textarea_field($_POST['emergency_notes']??''),'status'=>'scheduled','pickup_status'=>'pending','safari_status'=>'pending','hotel_status'=>'pending']); wp_safe_redirect(admin_url('admin.php?page=pwt-trip-operations')); exit; }
}
