<?php
declare(strict_types=1);
namespace PWT\Documents;
defined('ABSPATH') || exit;

use PWT\Bookings\Services\NotificationService;
use PWT\Payments\PaymentService;

final class DocumentService
{
    public function __construct(
        private readonly NotificationService $notifications,
        private readonly PaymentService $payments
    ) {
    }

    public function voucher(int $bookingId): array
    {
        $ctx = $this->notifications->context($bookingId);
        if ($ctx['booking_number'] === '') {
            return [];
        }
        $ctx['balance'] = $this->payments->balance($bookingId);
        $ctx['html'] = $this->renderDocument('voucher', $ctx);

        return $ctx;
    }

    public function invoice(int $bookingId): array
    {
        $ctx = $this->notifications->context($bookingId);
        if ($ctx['booking_number'] === '') {
            return [];
        }
        $ctx['balance'] = $this->payments->balance($bookingId);
        $ctx['html'] = $this->renderDocument('invoice', $ctx);

        return $ctx;
    }

    private function renderDocument(string $type, array $ctx): string
    {
        $siteName = wp_specialchars_decode((string) get_option('blogname'), ENT_QUOTES);
        $customer = (array) ($ctx['customer'] ?? []);
        $balance = (array) ($ctx['balance'] ?? []);
        $currency = (string) ($ctx['currency'] ?? 'INR');

        $metaRows = [
            [__('Booking Number', 'wildtours-plugin'), (string) $ctx['booking_number']],
            [__('Travel Dates', 'wildtours-plugin'), $this->dateRange((string) $ctx['travel_start'], (string) $ctx['travel_end'])],
            [__('Travelers', 'wildtours-plugin'), (string) ((int) $ctx['adults'] + (int) $ctx['children'])],
            [__('Customer', 'wildtours-plugin'), (string) ($customer['name'] ?? '')],
        ];

        $content = $this->infoTable($metaRows)
            . $this->itemsTable((array) $ctx['items'], $currency)
            . $this->travelersTable((array) $ctx['travelers']);

        if ($type === 'invoice') {
            $content .= $this->financialTable($balance, $currency);
        }

        return $this->documentLayout($siteName, $type, $content);
    }

    private function documentLayout(string $siteName, string $type, string $content): string
    {
        $title = $type === 'invoice'
            ? __('Invoice', 'wildtours-plugin')
            : __('Travel Voucher', 'wildtours-plugin');

        return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>' . esc_html($title) . '</title></head>'
            . '<body style="margin:0;padding:0;background:#eef1f4;font-family:Arial,Helvetica,sans-serif;">'
            . '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#eef1f4;"><tr><td align="center" style="padding:24px;">'
            . '<table role="presentation" width="760" cellpadding="0" cellspacing="0" style="max-width:760px;width:100%;background:#ffffff;border:1px solid #d9dee3;">'
            . '<tr><td style="padding:20px 28px;background:#0a7d4f;border-bottom:3px solid #086a43;">'
            . '<table width="100%" cellpadding="0" cellspacing="0"><tr>'
            . '<td style="color:#ffffff;font-size:20px;font-weight:bold;">' . esc_html($siteName) . '</td>'
            . '<td align="right" style="color:#eafff5;font-size:14px;">' . esc_html($title) . '</td>'
            . '</tr></table></td></tr>'
            . '<tr><td style="padding:28px;">' . $content . '</td></tr>'
            . '<tr><td style="padding:14px 28px;border-top:1px solid #eef1f4;color:#8a94a0;font-size:11px;">'
            . esc_html__('This document is system generated by', 'wildtours-plugin') . ' ' . esc_html($siteName)
            . '</td></tr>'
            . '</table></td></tr></table></body></html>';
    }

    private function infoTable(array $rows): string
    {
        return $this->table([
            [__('Reference', 'wildtours-plugin'), __('Value', 'wildtours-plugin')],
            ...$rows,
        ]);
    }

    private function itemsTable(array $items, string $currency): string
    {
        if (!$items) {
            return '';
        }

        $rows = [[__('Item', 'wildtours-plugin'), __('Dates', 'wildtours-plugin'), __('Qty', 'wildtours-plugin'), __('Total', 'wildtours-plugin')]];
        foreach ($items as $item) {
            $rows[] = [
                (string) ($item['name'] ?? ''),
                $this->dateRange((string) ($item['start_date'] ?? ''), (string) ($item['end_date'] ?? '')),
                (string) ($item['quantity'] ?? 1),
                $this->amount((float) ($item['total'] ?? 0), $currency),
            ];
        }

        return '<h3 style="margin:18px 0 8px;font-size:15px;color:#1a2b3c;">' . esc_html__('Booking Items', 'wildtours-plugin') . '</h3>' . $this->table($rows);
    }

    private function travelersTable(array $travelers): string
    {
        if (!$travelers) {
            return '';
        }

        $rows = [[__('Traveler', 'wildtours-plugin'), __('Passport', 'wildtours-plugin'), __('Nationality', 'wildtours-plugin')]];
        foreach ($travelers as $traveler) {
            $rows[] = [
                trim((string) ($traveler['first_name'] ?? '') . ' ' . (string) ($traveler['last_name'] ?? '')),
                (string) ($traveler['passport_number'] ?? ''),
                (string) ($traveler['nationality'] ?? ''),
            ];
        }

        return '<h3 style="margin:18px 0 8px;font-size:15px;color:#1a2b3c;">' . esc_html__('Travelers', 'wildtours-plugin') . '</h3>' . $this->table($rows);
    }

    private function financialTable(array $balance, string $currency): string
    {
        $rows = [
            [__('Total', 'wildtours-plugin'), $this->amount((float) ($balance['total'] ?? 0), $currency)],
            [__('Paid', 'wildtours-plugin'), $this->amount((float) ($balance['paid'] ?? 0), $currency)],
            [__('Refunded', 'wildtours-plugin'), $this->amount((float) ($balance['refunded'] ?? 0), $currency)],
            [__('Balance Due', 'wildtours-plugin'), $this->amount((float) ($balance['balance_due'] ?? 0), $currency)],
        ];

        return '<h3 style="margin:18px 0 8px;font-size:15px;color:#1a2b3c;">' . esc_html__('Financial Summary', 'wildtours-plugin') . '</h3>' . $this->table($rows);
    }

    private function table(array $rows): string
    {
        $html = '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin:6px 0;">';
        foreach ($rows as $index => $row) {
            $html .= '<tr>';
            foreach ($row as $cell) {
                $style = $index === 0
                    ? 'padding:8px 10px;text-align:left;background:#f3f5f7;border-bottom:1px solid #d9dee3;font-size:12px;font-weight:bold;color:#3a4a5a;'
                    : 'padding:8px 10px;text-align:left;border-bottom:1px solid #eef1f4;font-size:13px;';
                $html .= '<td style="' . $style . '">' . esc_html((string) $cell) . '</td>';
            }
            $html .= '</tr>';
        }
        return $html . '</table>';
    }

    private function dateRange(string $start, string $end): string
    {
        if ($start === '' && $end === '') {
            return '';
        }
        $fmt = static fn (string $d): string => date_i18n('j M Y', strtotime($d));
        return $start === $end || $end === '' ? $fmt($start) : $fmt($start) . ' - ' . $fmt($end);
    }

    private function amount(float $value, string $currency): string
    {
        return $currency . ' ' . number_format_i18n($value, 2);
    }
}